language: crystal

script:
  - crystal tool format --check
  - crystal spec
  - crystal docs

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  project_name: what_happen
  on:
    branch: master
  local_dir: docs
